# Generated by Django 4.1.2 on 2022-10-29 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
