# Generated by Django 4.1.2 on 2022-10-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Distance',
        ),
    ]
