# Generated by Django 4.1.2 on 2022-10-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0004_delete_collection_delete_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=100, max_digits=100)),
                ('latitude', models.DecimalField(decimal_places=100, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu_1', models.CharField(max_length=100)),
                ('lieu_2', models.CharField(max_length=100)),
                ('dist', models.IntegerField()),
            ],
        ),
    ]
