# Generated by Django 4.1.2 on 2022-10-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_dim'),
    ]

    operations = [
        migrations.CreateModel(
            name='inf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrice', models.CharField(max_length=300)),
                ('dim', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='dim',
        ),
    ]
