# Generated by Django 4.1.2 on 2022-10-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_inf_delete_dim'),
    ]

    operations = [
        migrations.CreateModel(
            name='bound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=10, max_digits=20)),
                ('chemin', models.CharField(max_length=300)),
            ],
        ),
    ]
